import fs from 'node:fs';
import {
  applyGlyphSpec,
  type GlyphContext,
} from '@shadow-garden/bapbong-contracts';
import { importDocx } from './docx';

/**
 * A .docx whose character tracking (w:spacing) and horizontal glyph scaling
 * (w:w) were written by LibreOffice — an implementation that had no part in
 * writing this package. Generated by scripts/make-glyph-scale-fixture.sh
 * (Docker; see that script's header). Committed so these checks run everywhere
 * without it.
 *
 * It exists for one question that hand-written XML cannot answer: when a run
 * carries BOTH, does the scale apply to the tracking as well as to the glyphs?
 * Seventeen runs in khbd.docx carry both, so the answer decides real pages.
 *
 * The generator settles it from LibreOffice's own PDF output, where the scale
 * lands in the text matrix and the tracking in the TJ array — and the tracking
 * comes out DIVIDED by the scale, so it survives the matrix at its absolute
 * value. Those numbers are not re-derived here (this suite must not need
 * Docker); what is checked here is that the same conclusion is wired into
 * applyGlyphSpec, and that the fixture still carries the case it was made for.
 */
const FIXTURE = new Uint8Array(
  fs.readFileSync(new URL('./__fixtures__/glyph-scale.docx', import.meta.url)),
);

/** Marks on the sample run of the line starting with `prefix`.
 *
 *  Each line is "<label>: <sample>" in two runs, and the sample is the LAST
 *  one — not "the one that has marks": LibreOffice puts a font and a size on
 *  the label too, so that rule reads the label every time. */
async function marksOfLine(prefix: string) {
  const { doc } = await importDocx(FIXTURE.buffer as ArrayBuffer);
  let found: Record<string, Record<string, unknown>> | null = null;
  doc.descendants((n) => {
    if (found || n.type.name !== 'paragraph') return;
    if (!n.textContent.startsWith(prefix)) return;
    let last: Record<string, Record<string, unknown>> | null = null;
    n.descendants((c) => {
      if (c.isText)
        last = Object.fromEntries(c.marks.map((m) => [m.type.name, m.attrs]));
    });
    found = last;
  });
  return found as Record<string, Record<string, unknown>> | null;
}

describe('LibreOffice glyph-scale fixture', () => {
  it('reads tracking that LibreOffice wrote', async () => {
    // 1.3pt in the source; LibreOffice chose 26 twips, which is the value
    // khbd.docx uses most.
    expect((await marksOfLine('tracked:'))?.['letterSpacing']).toEqual({
      twips: 26,
    });
  });

  it('reads horizontal scaling that LibreOffice wrote', async () => {
    expect((await marksOfLine('scaled:'))?.['charScale']).toEqual({
      percent: 80,
    });
  });

  it('reads both on one run — the case the fixture exists for', async () => {
    const marks = await marksOfLine('both:');
    expect(marks?.['letterSpacing']).toEqual({ twips: 26 });
    expect(marks?.['charScale']).toEqual({ percent: 80 });
  });

  it('leaves tracking absolute under a scale, as LibreOffice does', async () => {
    // 26 twips = 1.3pt = 1.7333px. Under an 80% scale the measurer multiplies
    // the whole measured width by 0.8, so the tracking handed to the context
    // has to be pre-divided to survive at its absolute value. Scaling the
    // tracking too would leave letterSpacing at 1.7333px here.
    const ctx: GlyphContext = { font: '', letterSpacing: '' };
    const px = (26 / 20) * (96 / 72);
    const scale = applyGlyphSpec(ctx, {
      family: 'Arial',
      sizePt: 12,
      bold: false,
      italic: false,
      letterSpacing: px,
      scaleX: 0.8,
    });
    expect(scale).toBe(0.8);
    expect(parseFloat(ctx.letterSpacing)).toBeCloseTo(px / 0.8, 6);
    // What the measurer ends up charging per character, after its own × scale.
    expect(parseFloat(ctx.letterSpacing) * scale).toBeCloseTo(px, 6);
  });
});
