import fs from 'node:fs';
import { CfbReader } from './cfb';
import { DocxImportError, sniffDocx } from './sniff';
import { importDocx } from './docx';
import { DocxCryptoError, parseEncryptionInfo } from './crypto-docx';

/**
 * A .docx encrypted by LibreOffice — an implementation that had no part in
 * writing this package. Generated by scripts/make-encrypted-fixture.sh (Docker;
 * see that script's header). Committed so these checks run everywhere without
 * it.
 *
 * It is deliberately a file we did NOT encrypt: verifying our reader against
 * our own writer is circular, and a wrong constant on both sides cancels out.
 */
const FIXTURE = new Uint8Array(
  fs.readFileSync(
    new URL('./__fixtures__/libreoffice-encrypted.docx', import.meta.url),
  ),
);
const PASSWORD = 'bapbong-test';

describe('a third party’s encrypted .docx', () => {
  it('is recognised as encrypted, not as some other broken file', () => {
    expect(sniffDocx(FIXTURE)).toBe('encrypted');
  });

  it('opens as a container we can read the streams out of', () => {
    const r = new CfbReader(FIXTURE);
    expect(r.streamNames()).toEqual(
      expect.arrayContaining(['EncryptionInfo', 'EncryptedPackage']),
    );
  });

  // What this fixture actually proved: LibreOffice writes the OLDER scheme.
  // Word 2007 wrote it too, so these files are out there — and we only
  // implement Agile. The check is pinned to today's behaviour so the day
  // Standard lands, this test fails and gets rewritten into a real decrypt.
  it('uses Standard (3.2) encryption, which we do not implement yet', () => {
    const info = new CfbReader(FIXTURE).readStream('EncryptionInfo');
    expect(info).not.toBeNull();
    expect(() => parseEncryptionInfo(info!)).toThrow(DocxCryptoError);
    expect(() => parseEncryptionInfo(info!)).toThrow(/3\.2|only Agile/);
  });

  it('fails as a classified dead end, so no UI loops asking for a password', async () => {
    const err = await importDocx(FIXTURE, { password: PASSWORD }).catch(
      (e) => e as DocxImportError,
    );
    expect(err).toBeInstanceOf(DocxImportError);
    // NOT 'wrong-password' — the password is right; the scheme is the problem,
    // and telling those apart is what keeps the unlock prompt honest.
    expect(err.kind).toBe('unsupported-encryption');
  });
});
