import fs from 'node:fs';
import { importDocx } from './docx';

/**
 * A .docx whose tab stops were written by LibreOffice — an implementation that
 * had no part in writing this package. Generated by scripts/make-tabs-fixture.sh
 * (Docker; see that script's header). Committed so these checks run everywhere
 * without it.
 *
 * It exists because apps/playground/public/sample.docx claims to demo w:tabs
 * but carries none (a Google Docs round-trip flattened every tab into plain
 * text), so the tab path had no realistic fixture: only hand-written XML in
 * docx.spec.ts, which proves the parser agrees with itself.
 */
const FIXTURE = new Uint8Array(
  fs.readFileSync(new URL('./__fixtures__/tab-stops.docx', import.meta.url)),
);

/** Paragraphs that actually contain a tab character, in document order. */
async function tabParagraphs() {
  const { doc } = await importDocx(FIXTURE.buffer as ArrayBuffer);
  const out: { text: string; tabs: { pos: number; val: string; leader?: string }[] | null }[] = [];
  doc.descendants((n) => {
    if (n.type.name === 'paragraph' && n.textContent.includes('\t')) {
      out.push({
        text: n.textContent,
        tabs: n.attrs['tabs'] as { pos: number; val: string; leader?: string }[] | null,
      });
    }
  });
  return out;
}

describe('a third party’s tab stops', () => {
  it('keeps the tab characters as tabs, not as collapsed whitespace', async () => {
    const paras = await tabParagraphs();
    // 3 TOC lines + 2 signature lines + 3 price lines + 1 default-grid line.
    expect(paras).toHaveLength(9);
    expect(paras[0].text).toBe('Chương 1 — Mở đầu\t3');
  });

  it('reads a right stop with a dot leader (table of contents)', async () => {
    const [toc] = await tabParagraphs();
    expect(toc.tabs).toHaveLength(1);
    expect(toc.tabs?.[0]).toMatchObject({ val: 'right', leader: 'dot' });
    // 16cm from the text left edge ≈ 605px at 96dpi.
    expect(toc.tabs?.[0].pos).toBeGreaterThan(590);
    expect(toc.tabs?.[0].pos).toBeLessThan(620);
  });

  it('reads centred stops (signature block)', async () => {
    const sign = (await tabParagraphs()).find((p) => p.text.startsWith('NGƯỜI LẬP'));
    expect(sign?.text).toBe('NGƯỜI LẬP\tKẾ TOÁN\tGIÁM ĐỐC');
    expect(sign?.tabs?.map((t) => t.val)).toEqual(['center', 'center', 'center']);
    // Ascending and evenly spaced across the text width. Within 2px: the
    // stops travel cm → twips → px and each rounds independently.
    const pos = sign?.tabs?.map((t) => t.pos) ?? [];
    expect(pos[0]).toBeLessThan(pos[1]);
    expect(pos[1]).toBeLessThan(pos[2]);
    expect(Math.abs(pos[1] - pos[0] - (pos[2] - pos[1]))).toBeLessThanOrEqual(2);
  });

  it('reads a decimal stop (price column aligned on the comma)', async () => {
    const price = (await tabParagraphs()).find((p) => p.text.startsWith('Phí khởi tạo'));
    expect(price?.tabs?.map((t) => t.val)).toEqual(['left', 'decimal']);
  });

  it('leaves a paragraph without declared stops on the default grid', async () => {
    const plain = (await tabParagraphs()).find((p) => p.text.startsWith('Cột A'));
    expect(plain?.text).toBe('Cột A\tCột B\tCột C — rơi vào lưới tab mặc định.');
    // No w:tabs of its own: the layout engine falls back to its 0.5in grid.
    expect(plain?.tabs).toBeNull();
  });
});
